name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_animated_dialog: ^2.0.1
  awesome_dialog: ^2.2.1
  dropdown_search: ^3.0.1
  file_picker: ^4.6.1
  flutter_multi_select_items: ^0.4.2
  dartz: ^0.10.0
  dart_appwrite: ^6.0.1
  appwrite: ^6.0.0
  flutter_typeahead: ^4.0.0
  printing: ^5.9.2
  url_launcher: ^6.1.6
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

